src/Meedule/MeetingBundle/Entity/Meeting.php
<?php

namespace Meedule\MeetingBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Meedule\UserBundle\Entity\User;

/**
 * Meedule\MeetingBundle\Entity\Meeting
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Meedule\MeetingBundle\Entity\MeetingRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Meeting
{
    function __construct(){
        $this->setCreatedAt(new \DateTime());
    }
    
    /**
     * @var integer $id
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string $title
     *
     * @ORM\Column(name="title", type="string", length=255)
     * @Assert\NotBlank()
     */
    private $title;

    /**
     * @var date $date
     *
     * @ORM\Column(name="date", type="date", nullable="true")
     */
    private $date;
    
    /**
     * @var time $time
     *
     * @ORM\Column(name="time", type="time", nullable="true")
     */
    private $time;
    
    /**
     * @var int $duration
     *
     * @ORM\Column(name="duration", type="float", nullable="true")
     */
    private $duration;

    /**
     * @var text $description
     *
     * @ORM\Column(name="description", type="text", nullable="true")
     */
    private $description;

    /**
     * @var text $address
     *
     * @ORM\Column(name="address", type="text", nullable="true")
     */
    private $address;
    
    /**
     * @var boolea $closed
     *
     * @ORM\Column(name="closed", type="boolean", nullable="true")
     */
    private $closed;
    
    /**
     * @var datetime $closedAt
     *
     * @ORM\Column(name="closedAt", type="datetime", nullable="true")
     */
    private $closedAt;

    /**
     * @var datetime $createdAt
     *
     * @ORM\Column(name="createdAt", type="datetime")
     */
    private $createdAt;
    
    /**
     * @var string $slugpublic
     *
     * @ORM\Column(name="slugpublic", type="string", length=32, unique=true)
     */
    private $slugpublic;
    
    /**
     * @var string $slugprivate
     *
     * @ORM\Column(name="slugprivate", type="string", length=32, unique=true)
     */
    private $slugprivate;
    
    /**
     * @var string $mail
     * 
     * @ORM\Column(name="mail", type="string", length=255)
     * @Assert\NotBlank()
     */
    private $mail;
    
    /**
     * @var string $name
     * 
     * @ORM\Column(name="name", type="string", length=255)
     * @Assert\NotBlank()
     */
    private $name;
    
    /**
     * @ORM\ManyToOne(targetEntity="Meedule\UserBundle\Entity\User", inversedBy="meedules")
     * @ORM\JoinColumn(name="owner_id", referencedColumnName="id")
     */
    private $owner;
    
    /**
     * @ORM\OneToMany(targetEntity="Meedule\MeetingBundle\Entity\Attendee", mappedBy="meeting", cascade={"persist", "remove"})
     */
    private $attendees;
    
    /**
     * @ORM\OneToMany(targetEntity="Meedule\MeetingBundle\Entity\Topic", mappedBy="meeting", cascade={"persist", "remove"})
     * @ORM\OrderBy({"position" = "ASC", "id" = "ASC"})
     */
    private $topics;
    
    /**
     * @var string $doodle
     *
     * @ORM\Column(name="doodle", type="string", length=255, nullable="true")
     */
    private $doodle;
    
    /**
     * @ORM\OneToMany(targetEntity="Meedule\MeetingBundle\Entity\Reference", mappedBy="meeting", cascade={"persist", "remove"})
     */
    private $references;
    
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     */
    public function setTitle($title)
    {
        $this->title = $title;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set description
     *
     * @param text $description
     */
    public function setDescription($description)
    {
        $this->description = $description;
    }

    /**
     * Get description
     *
     * @return text 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set address
     *
     * @param text $address
     */
    public function setAddress($address)
    {
        $this->address = $address;
    }

    /**
     * Get address
     *
     * @return text 
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Set createdAt
     *
     * @param datetime $createdAt
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    }

    /**
     * Get createdAt
     *
     * @return datetime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set mail
     *
     * @param string $mail
     */
    public function setMail($mail)
    {
        $this->mail = $mail;
    }

    /**
     * Get mail
     *
     * @return string 
     */
    public function getMail()
    {
        return $this->mail;
    }

    /**
     * Set duration
     *
     * @param float $duration
     */
    public function setDuration($duration)
    {
        $this->duration = $duration;
    }

    /**
     * Get duration
     *
     * @return float 
     */
    public function getDuration()
    {
        return $this->duration;
    }

    /**
     * Set date
     *
     * @param date $date
     */
    public function setDate($date)
    {
        $this->date = $date;
    }

    /**
     * Get date
     *
     * @return date 
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set time
     *
     * @param time $time
     */
    public function setTime($time)
    {
        $this->time = $time;
    }

    /**
     * Get time
     *
     * @return time 
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * Set slugpublic
     *
     * @param string $slugpublic
     */
    public function setSlugpublic($slugpublic)
    {
        $this->slugpublic = $slugpublic;
    }

    /**
     * Get slugpublic
     *
     * @return string 
     */
    public function getSlugpublic()
    {
        return $this->slugpublic;
    }

    /**
     * Set slugprivate
     *
     * @param string $slugprivate
     */
    public function setSlugprivate($slugprivate)
    {
        $this->slugprivate = $slugprivate;
    }

    /**
     * Get slugprivate
     *
     * @return string 
     */
    public function getSlugprivate()
    {
        return $this->slugprivate;
    }

    /**
     * Set name
     *
     * @param string $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }
    
    /**
    * @ORM\PrePersist
    */
    public function setSlugs()
    {
        if(!$this->getSlugpublic()){
            $data = new \DateTime();
            $string = $this->getTitle() . $this->getMail() . $data->format('YmsHis') . rand(1,1000000);
            $this->setSlugpublic(substr(md5($string), rand(0,1), 16));
            $this->setSlugprivate(substr(md5(strrev($string)), rand(0,1), 16));
        }
    }

    public function hasAttendee(Attendee $attendee){
        $key = $this->attendees->indexOf($attendee);
        if($key===FALSE) 
        {
            return false;
        }
        return true;
    }

    /**
     * Add topics
     *
     * @param Meedule\MeetingBundle\Entity\Topic $topics
     */
    public function addTopic(\Meedule\MeetingBundle\Entity\Topic $topics)
    {
        $this->topics[] = $topics;
    }

    /**
     * Get topics
     *
     * @return Doctrine\Common\Collections\Collection 
     */
    public function getTopics()
    {
        return $this->topics;
    }
    
    /**
     * @return Doctrine\Common\Collections\Collection 
     */
    public function getAgendaTopics()
    {
        $topics = new ArrayCollection;
        foreach ($this->getTopics() as $topic) {
            if (!$topic->getOwner()) {
                $topics->add($topic);
            }
        }

        return $topics;
    }
    
    /**
     * @return Doctrine\Common\Collections\Collection 
     */
    public function getCrewTopics()
    {
        $topics = new ArrayCollection;
        foreach ($this->getTopics() as $topic) {
            if ($topic->getOwner()) {
                $topics->add($topic);
            }
        }

        return $topics;
    }

    /**
     * Set doodle
     *
     * @param string $doodle
     */
    public function setDoodle($doodle)
    {
        $this->doodle = $doodle;
    }

    /**
     * Get doodle
     *
     * @return string 
     */
    public function getDoodle()
    {
        return $this->doodle;
    }
    
    public function setAgendaTopics(ArrayCollection $topics){}
    
    public function setCrewTopics(ArrayCollection $topics){}

    /**
     * Set closed
     *
     * @param boolean $closed
     */
    public function setClosed($closed)
    {
        $this->closed = $closed;
    }

    /**
     * Get closed
     *
     * @return boolean 
     */
    public function getClosed()
    {
        return $this->closed;
    }

    /**
     * Set closedAt
     *
     * @param datetime $closedAt
     */
    public function setClosedAt($closedAt)
    {
        $this->closedAt = $closedAt;
    }

    /**
     * Get closedAt
     *
     * @return datetime 
     */
    public function getClosedAt()
    {
        return $this->closedAt;
    }
    
    /**
     * Is Closed
     *
     * @return boolean 
     */
    public function isClosed()
    {
        return $this->closed;
    }
    
    public function getMailGravatar()
    {
        if($this->mail){
            return md5(strtolower($this->mail));
        }
        return false;

src/Meedule/MeetingBundle/Resources/views/Admin/admin.html.twig
{% extends 'MeeduleMeetingBundle:Meeting:show.html.twig' %}

{% block commands %}
    {% if not entity.isClosed %}
        <a href="{{ path('meeting_admin_edit', {'slug': entity.slugprivate}) }}" class="btn btn-small">Modifica <i class="icon-wrench"></i></a><br />
        <a href="{{ path('meeting_admin_finalize', {'slug': entity.slugprivate}) }}" class="btn btn-small">Chiudi <i class="icon-ok"></i></a><br />
    {% endif %}
{% endblock %}
    
{% block agenda_topics %}
    {% if not entity.isClosed %}
        {% include 'MeeduleMeetingBundle:Meeting:_topics.html.twig' with {'topics': topics_agenda, 'url_topic_delete': url_delete_topic_agenda, 'topics_id': 'topics_agenda', 'with_icon_vertical': true} %}
    {% else %}
        {% include 'MeeduleMeetingBundle:Meeting:_topics.html.twig' with {'topics': topics_agenda, 'topics_id': 'topics_agenda'} %}
    {% endif %}
{% endblock %}
    
{% block crew_topics %}
    {% if not entity.isClosed %}
        {% include 'MeeduleMeetingBundle:Meeting:_topics.html.twig' with {'topics': topics_crew, 'url_topic_delete': url_delete_topic_crew, 'topics_id': 'topics_crew', 'with_picture': true} %}
    {% else %}
        {% include 'MeeduleMeetingBundle:Meeting:_topics.html.twig' with {'topics': topics_crew, 'topics_id': 'topics_crew', 'with_picture': true} %}
    {% endif %}
{% endblock %}
    
{% block form_create_topic_agenda %}
    {% if not entity.isClosed %}
        <form action="{{ path(url_create_topic_agenda, {'slug': slug }) }}" method="post" {{ form_enctype(form_create_topic_agenda) }} class="form-horizontal">
            {{ form_widget(form_create_topic_agenda.name) }}
            {{ form_rest(form_create_topic_agenda) }}
            <button type="submit" class="btn btn-primary btn-small">Aggiungi</button>
        </form>
    {% endif %}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {% if not entity.isClosed %}
        <script>
            $("#topics_agenda").addClass('sortable');
            $("#topics_agenda").sortable({
                cursor: 'move',
                stop: function( event, ui ) {
                    $.ajax({
                        type: 'POST',
                        url: '{{ path('meeting_topic_order', {'slug': slug}) }}',
                        data: $(this).sortable("serialize")
                    });
                }
            });
        </script>
    {% endif %}
{% endblock %}

src/Meedule/MeetingBundle/Resources/views/Admin/edit.html.twig
{% extends 'MeeduleDesignBundle::layout.html.twig' %}

{% block content %}
    

    <h1>Modifica il tuo evento</h1>
    <hr />
    
    <form action="{{ path('meeting_admin_update', {'slug': entity.slugprivate}) }}" method="post" {{ form_enctype(form) }} class="form-horizontal">
        {{ form_widget(form) }}
        
        <div class="form-actions">
            <button type="submit" class="btn btn-success btn-large">Salva</button>
            o <a href="{{ path('meeting_admin', {'slug': entity.slugprivate}) }}">
                indietro
            </a>
         </div>
    </form>

{% endblock %}

src/Meedule/MeetingBundle/Resources/views/Admin/finalize.html.twig
{% extends 'MeeduleDesignBundle::layout.html.twig' %}

{% block content %}
    

    <h1>Chiudi "{{ entity.title }}"</h1>
    <hr />
    <p>
        Il tuo meeting sta per essere chiuso. Non sarà dunque possibile aggiungere ulteriori registrazioni o argomenti.
    </p>
    
    <form action="{{ path('meeting_admin_close', {'slug': entity.slugprivate}) }}" method="post" {{ form_enctype(form) }} class="form-horizontal">
        <h3>Agenda</h3>
        {% for topic in form.AgendaTopics %}
            <label class="checkbox">
                {{ form_widget(topic.approved) }}
                {{ entity.agendaTopics[loop.index0].name }}
            </label>
        {% endfor %}
        
        <h4>Argomenti Proposti</h4>
        {% for topic in form.CrewTopics %}
            <label class="checkbox">
                {{ form_widget(topic.approved) }}
                {{ entity.crewTopics[loop.index0].name }}
            </label>
        {% endfor %}
        
        {{ form_rest(form) }}
        
        <div class="form-actions">
            <button type="submit" class="btn btn-success btn-large">Salva</button>
            o <a href="{{ path('meeting_admin', {'slug': entity.slugprivate}) }}">
                indietro
            </a>
         </div>
    </form>

{% endblock %}