src/Meedule/MeetingBundle/Entity/Meeting.php
<?php

namespace Meedule\MeetingBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Meedule\UserBundle\Entity\User;

/**
 * Meedule\MeetingBundle\Entity\Meeting
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Meedule\MeetingBundle\Entity\MeetingRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Meeting
{
    function __construct(){
        $this->setCreatedAt(new \DateTime());
    }
    
    /**
     * @var integer $id
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string $title
     *
     * @ORM\Column(name="title", type="string", length=255)
     * @Assert\NotBlank()
     */
    private $title;

    /**
     * @var date $date
     *
     * @ORM\Column(name="date", type="date", nullable="true")
     */
    private $date;
    
    /**
     * @var time $time
     *
     * @ORM\Column(name="time", type="time", nullable="true")
     */
    private $time;
    
    /**
     * @var int $duration
     *
     * @ORM\Column(name="duration", type="float", nullable="true")
     */
    private $duration;

    /**
     * @var text $description
     *
     * @ORM\Column(name="description", type="text", nullable="true")
     */
    private $description;

    /**
     * @var text $address
     *
     * @ORM\Column(name="address", type="text", nullable="true")
     */
    private $address;
    
    /**
     * @var boolea $closed
     *
     * @ORM\Column(name="closed", type="boolean", nullable="true")
     */
    private $closed;
    
    /**
     * @var datetime $closedAt
     *
     * @ORM\Column(name="closedAt", type="datetime", nullable="true")
     */
    private $closedAt;

    /**
     * @var datetime $createdAt
     *
     * @ORM\Column(name="createdAt", type="datetime")
     */
    private $createdAt;
    
    /**
     * @var string $slugpublic
     *
     * @ORM\Column(name="slugpublic", type="string", length=32, unique=true)
     */
    private $slugpublic;
    
    /**
     * @var string $slugprivate
     *
     * @ORM\Column(name="slugprivate", type="string", length=32, unique=true)
     */
    private $slugprivate;
    
    /**
     * @var string $mail
     * 
     * @ORM\Column(name="mail", type="string", length=255)
     * @Assert\NotBlank()
     */
    private $mail;
    
    /**
     * @var string $name
     * 
     * @ORM\Column(name="name", type="string", length=255)
     * @Assert\NotBlank()
     */
    private $name;
    
    /**
     * @ORM\ManyToOne(targetEntity="Meedule\UserBundle\Entity\User", inversedBy="meedules")
     * @ORM\JoinColumn(name="owner_id", referencedColumnName="id")
     */
    private $owner;
    
    /**
     * @ORM\OneToMany(targetEntity="Meedule\MeetingBundle\Entity\Attendee", mappedBy="meeting", cascade={"persist", "remove"})
     */
    private $attendees;
    
    /**
     * @ORM\OneToMany(targetEntity="Meedule\MeetingBundle\Entity\Topic", mappedBy="meeting", cascade={"persist", "remove"})
     * @ORM\OrderBy({"position" = "ASC", "id" = "ASC"})
     */
    private $topics;
    
    /**
     * @var string $doodle
     *
     * @ORM\Column(name="doodle", type="string", length=255, nullable="true")
     */
    private $doodle;
    
    /**
     * @ORM\OneToMany(targetEntity="Meedule\MeetingBundle\Entity\Reference", mappedBy="meeting", cascade={"persist", "remove"})
     */
    private $references;
    
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     */
    public function setTitle($title)
    {
        $this->title = $title;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set description
     *
     * @param text $description
     */
    public function setDescription($description)
    {
        $this->description = $description;
    }

    /**
     * Get description
     *
     * @return text 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set address
     *
     * @param text $address
     */
    public function setAddress($address)
    {
        $this->address = $address;
    }

    /**
     * Get address
     *
     * @return text 
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Set createdAt
     *
     * @param datetime $createdAt
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    }

    /**
     * Get createdAt
     *
     * @return datetime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set mail
     *
     * @param string $mail
     */
    public function setMail($mail)
    {
        $this->mail = $mail;
    }

    /**
     * Get mail
     *
     * @return string 
     */
    public function getMail()
    {
        return $this->mail;
    }

    /**
     * Set duration
     *
     * @param float $duration
     */
    public function setDuration($duration)
    {
        $this->duration = $duration;
    }

    /**
     * Get duration
     *
     * @return float 
     */
    public function getDuration()
    {
        return $this->duration;
    }

    /**
     * Set date
     *
     * @param date $date
     */
    public function setDate($date)
    {
        $this->date = $date;
    }

    /**
     * Get date
     *
     * @return date 
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set time
     *
     * @param time $time
     */
    public function setTime($time)
    {
        $this->time = $time;
    }

    /**
     * Get time
     *
     * @return time 
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * Set slugpublic
     *
     * @param string $slugpublic
     */
    public function setSlugpublic($slugpublic)
    {
        $this->slugpublic = $slugpublic;
    }

    /**
     * Get slugpublic
     *
     * @return string 
     */
    public function getSlugpublic()
    {
        return $this->slugpublic;
    }

    /**
     * Set slugprivate
     *
     * @param string $slugprivate
     */
    public function setSlugprivate($slugprivate)
    {
        $this->slugprivate = $slugprivate;
    }

    /**
     * Get slugprivate
     *
     * @return string 
     */
    public function getSlugprivate()
    {
        return $this->slugprivate;
    }

    /**
     * Set name
     *
     * @param string $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }
    
    /**
    * @ORM\PrePersist
    */
    public function setSlugs()
    {
        if(!$this->getSlugpublic()){
            $data = new \DateTime();
            $string = $this->getTitle() . $this->getMail() . $data->format('YmsHis') . rand(1,1000000);
            $this->setSlugpublic(substr(md5($string), rand(0,1), 16));
            $this->setSlugprivate(substr(md5(strrev($string)), rand(0,1), 16));
        }
    }

    public function hasAttendee(Attendee $attendee){
        $key = $this->attendees->indexOf($attendee);
        if($key===FALSE) 
        {
            return false;
        }
        return true;
    }

    /**
     * Add topics
     *
     * @param Meedule\MeetingBundle\Entity\Topic $topics
     */
    public function addTopic(\Meedule\MeetingBundle\Entity\Topic $topics)
    {
        $this->topics[] = $topics;
    }

    /**
     * Get topics
     *
     * @return Doctrine\Common\Collections\Collection 
     */
    public function getTopics()
    {
        return $this->topics;
    }
    
    /**
     * @return Doctrine\Common\Collections\Collection 
     */
    public function getAgendaTopics()
    {
        $topics = new ArrayCollection;
        foreach ($this->getTopics() as $topic) {
            if (!$topic->getOwner()) {
                $topics->add($topic);
            }
        }

        return $topics;
    }
    
    /**
     * @return Doctrine\Common\Collections\Collection 
     */
    public function getCrewTopics()
    {
        $topics = new ArrayCollection;
        foreach ($this->getTopics() as $topic) {
            if ($topic->getOwner()) {
                $topics->add($topic);
            }
        }

        return $topics;
    }

    /**
     * Set doodle
     *
     * @param string $doodle
     */
    public function setDoodle($doodle)
    {
        $this->doodle = $doodle;
    }

    /**
     * Get doodle
     *
     * @return string 
     */
    public function getDoodle()
    {
        return $this->doodle;
    }
    
    public function setAgendaTopics(ArrayCollection $topics){}
    
    public function setCrewTopics(ArrayCollection $topics){}

    /**
     * Set closed
     *
     * @param boolean $closed
     */
    public function setClosed($closed)
    {
        $this->closed = $closed;
    }

    /**
     * Get closed
     *
     * @return boolean 
     */
    public function getClosed()
    {
        return $this->closed;
    }

    /**
     * Set closedAt
     *
     * @param datetime $closedAt
     */
    public function setClosedAt($closedAt)
    {
        $this->closedAt = $closedAt;
    }

    /**
     * Get closedAt
     *
     * @return datetime 
     */
    public function getClosedAt()
    {
        return $this->closedAt;
    }
    
    /**
     * Is Closed
     *
     * @return boolean 
     */
    public function isClosed()
    {
        return $this->closed;
    }
    
    public function getMailGravatar()
    {
        if($this->mail){
            return md5(strtolower($this->mail));
        }
        return false;

src/Meedule/MeetingBundle/Entity/User.php
<?php

namespace Meedule\MeetingBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Meedule\MeetingBundle\Entity\User
 *
 * @ORM\Table()
 * @ORM\Entity
 */
class User
{
    /**
     * @var integer $id
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string $name
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;
    
    /**
     * @var string $mail
     *
     * @ORM\Column(name="mail", type="string", length=255, nullable="true")
     */
    private $mail;

    /**
     * @ORM\ManyToOne(targetEntity="Meedule\MeetingBundle\Entity\Meeting", inversedBy="attendees")
     * @ORM\JoinColumn(name="meeting_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $meeting;
    
    private $delete_form;
    
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set meeting
     *
     * @param Meedule\MeetingBundle\Entity\Meeting $meeting
     */
    public function setMeeting(\Meedule\MeetingBundle\Entity\Meeting $meeting)
    {
        $this->meeting = $meeting;
    }

    /**
     * Get meeting
     *
     * @return Meedule\MeetingBundle\Entity\Meeting 
     */
    public function getMeeting()
    {
        return $this->meeting;
    }
    
    public function setDeleteForm($form){
        $this->delete_form = $form;
    }
    
    public function getDeleteForm(){
        return $this->delete_form;
    }

    /**
     * Set mail
     *
     * @param string $mail
     */
    public function setMail($mail)
    {
        $this->mail = $mail;
    }

    /**
     * Get mail
     *
     * @return string 
     */
    public function getMail()
    {
        return $this->mail;
    }
    
    /**
     * Get mail
     *
     * @return string 
     */
    public function getGravatarMail()
    {
        if($this->mail){
            return md5(strtolower($this->mail));
        }
        return false;
    }
}

src/Meedule/MeetingBundle/Form/MeetingType.php
<?php

namespace Meedule\MeetingBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilder;
use Meedule\MeetingBundle\Form\Type\DoodleType;
use Meedule\MeetingBundle\Form\Type\MailType;

class MeetingType extends AbstractType
{
    public function buildForm(FormBuilder $builder, array $options)
    {
        $builder
            ->add('title', 'text', array(
                'attr' => array('placeholder' => 'Riunione di bilancio'),
            ))
            ->add('mail', new MailType(),array(
                'attr' => array('placeholder' => 'mariorossi@gmail.com'),
            ))
            ->add('name', 'text', array(
                'attr' => array('placeholder' => 'Mario Rossi'),
            ))
            ->add('date', 'date', array(
                'format' => 'dd/MMM/yyyy',
                'years' => array(date('Y'), date('Y')+1, date('Y')+2, date('Y')+3, date('Y')+4),
            ))
            ->add('time','time',array(
                'hours' => array(8,9,10,11,12,13,14,15,16,17,18,19,20,21),
                'minutes' => array(0,15,30,45),
            ))
            ->add('duration', 'choice', array(
                'required' => false,
                'choices' => array(
                    '10' => '10 minuti',
                    '20' => '20 minuti',
                    '30' => '30 minuti',
                    '60' => '1 ora', 
                    '90' => '1 ora e mezza', 
                    '120' => '2 ore',
                    '180' => '3 ore',
                    )
            ))
            ->add('doodle', new DoodleType(), array(
                'required' => false,
            ))
            ->add('address', 'text', array(
                'required' => false,
                'attr' => array('placeholder' => 'Roma, via del corso'),
            ))
            ->add('description', 'textarea', array(
                'required' => false,
                'attr' => array('placeholder' => 'Note ulteriori del tuo meeting'),
            ))
        ;
    }

    public function getName()
    {
        return 'meedule_meetingbundle_meetingtype';
    }
}

src/Meedule/MeetingBundle/Resources/views/Meeting/_attendees.html.twig
<h5>Partecipanti <span class="badge">{{ attendees|length }}</span></h5>
{% if attendees %}
    {% for attendee in attendees %}
        <div class="attendee">
            {% if attendee.deleteForm %}
                <form 
                    action="{{ path(url_delete_attendee, {'slug': slug, 'id': attendee.id }) }}" 
                    method="post"
                    class="delete_form pull-right"
                    >
                    {{ form_widget(attendee.deleteForm) }}
                    <button type="submit"><i class="icon-trash"></i></button> 
                </form>
            {% endif %}
            <img 
                rel="tooltip"
                title="Immagine fornita da Gravatar.com"
                src="http://www.gravatar.com/avatar/{{attendee.gravatarMail}}?s=26&d=http://meedule.abmundi.com/gravatar.png" />
            {{ attendee.name }}
            <div class="clearfix"></div>
        </div>
    {% endfor %}
{% endif %}

{% if not entity.isClosed %}
    <a class="btn btn-success btn-small" data-toggle="#add_attendee">Voglio partecipare anche io</a>
    
    <form action="{{ path(url_create_attendee, {'slug': slug }) }}" method="post" {{ form_enctype(form) }} class="form-vertical" id="add_attendee">

        {{ form_widget(form) }}

        <button type="submit" class="btn btn-primary btn-small">Partecipa</button>
    </form>
{% endif %}

src/Meedule/MeetingBundle/Resources/views/Meeting/_detail.html.twig
Creato da <img 
    rel="tooltip"
    title="Immagine fornita da Gravatar.com"
    src="http://www.gravatar.com/avatar/{{entity.mailGravatar}}?s=24" /> {{ entity.name }}
{% if entity.date %}
    <br />
    <i class="icon-calendar"></i> {{ entity.date|date(date_simple_format)}}
    {% if entity.time %}
        - {{ entity.time|date(time)}}
    {% endif %}
{% endif %}
{% if entity.address %}
    <a 
        class="btn btn-small"
        target="_blank"
        href="https://maps.google.it/?t=m&amp;q={{ entity.address}}">
        <i class="icon-globe"></i> 
    </a>
    {{ entity.address}} 
{% endif %}
{% if entity.description %}
    <p>{{ entity.description }}</p>
{% endif %}
{% if entity.doodle %}
    <br />
    <img src={{ asset('bundles/meeduledesign/img/doodle.ico') }} />
    <a 
        target="_blank"
        href="{{ entity.doodle }}">
        Doodle
    </a>
{% endif %}

src/Meedule/MeetingBundle/Resources/views/Meeting/_references.html.twig
{% if entity.references %}
    <ol id="references">
    {% for reference in entity.references %}
        <li id="reference_{{ reference.id }}">
            {% if reference.deleteForm %}
                <form 
                    action="{{ path(url_reference_delete, {'slug': slug, 'id': reference.id }) }}"
                    method="post"
                    class="delete_form pull-right"
                    >
                    {{ form_widget(reference.deleteForm) }}
                    <button type="submit"><i class="icon-trash"></i></button> 
                </form>
            {% endif %}
            <a href="{{ reference.url }}" target="_blank">{{ reference.name }}</a>
            {% if reference.owner %}
                 [<em>{{ reference.owner }} <i class="icon-user"></i></em>] 
            {% endif %}
            <div class="clearfix"></div>
        </li>
    {% endfor %}
    </ol>
{% endif %}

src/Meedule/MeetingBundle/Resources/views/Meeting/_topics.html.twig
{% if topics %}
    <ol id="{{ topics_id }}" class="topics">
    {% for topic in topics %}
        <li id="topic_{{ topic.id }}"{% if entity.isClosed and not topic.isApproved %} class="rejected"{% endif %}>
            {% if topic.deleteForm %}
                <form 
                    action="{{ path(url_topic_delete, {'slug': slug, 'id': topic.id }) }}"
                    method="post"
                    class="delete_form pull-right"
                    >
                    {{ form_widget(topic.deleteForm) }}
                    <button type="submit"><i class="icon-trash"></i></button> 
                </form>
            {% endif %}
            {% if with_picture|default(false) and topic.user %}
                <img 
                    rel="tooltip"
                    title="Immagine fornita da Gravatar.com"
                    src="http://www.gravatar.com/avatar/{{topic.user.gravatarMail}}?s=26&d=http://meedule.abmundi.com/gravatar.png" />
            {% endif %}
            {% if with_icon_vertical|default(false) %}
                <i class="icon-resize-vertical"></i> 
            {% endif %}
            {{ topic.name }}
            {% if topic.owner %}
                 - <em>{{ topic.owner }}</em>
            {% endif %}
            {% if topic.deleteForm %}
                <div class="clearfix"></div>
            {% endif %}
        </li>
    {% endfor %}
    </ol>
{% endif %}

src/Meedule/MeetingBundle/Resources/views/Meeting/show.html.twig
{% extends 'MeeduleDesignBundle::layout.html.twig' %}

{% block title %}Meedule: {{ entity.title }}{% endblock %}

{% block meta %}
    <meta property="og:title" content="Meedule: {{ entity.title }}" />
    <meta property="og:description" content="{{ entity.description }}" />
    <meta property="og:url" content="{{ url('meeting_show', {'slug': entity.slugPublic} ) }}" />
{% endblock %}

{% block content %}

    <div class="container">

        <h1>{{ entity.title }}</h1>

        <div class="row">
            <div class="span8">
                <div class="well">
                    <h3>Agenda</h3>
                    {% block agenda_topics %}
                        {% include 'MeeduleMeetingBundle:Meeting:_topics.html.twig' with {'topics': topics_agenda, 'topics_id': 'topics_agenda'} %}
                    {% endblock %}
                    {% block form_create_topic_agenda %}{% endblock %}

                    <hr />
                    <h4>Argomenti proposti <span class="badge">{{ topics_crew|length }}</span></h4>
                    {% block crew_topics %}
                        {% include 'MeeduleMeetingBundle:Meeting:_topics.html.twig' with {'topics': topics_crew, 'url_topic_delete': url_delete_topic_crew, 'topics_id': 'topics_crew', 'with_picture': true} %}
                    {% endblock %}

                    {% if not entity.isClosed %}
                        <a class="btn btn-success btn-small" data-toggle="#add_topic">Voglio aggiungere un argomento</a>

                        <form action="{{ path(url_create_topic_crew, {'slug': slug }) }}" method="post" {{ form_enctype(form_create_topic_crew) }} class="form-horizontal" id="add_topic">
                            {{ form_widget(form_create_topic_crew.name) }}
                            {{ form_widget(form_create_topic_crew.owner) }}
                            {{ form_rest(form_create_topic_crew) }}
                            <button type="submit" class="btn btn-primary btn-small">Aggiungi</button>
                        </form>
                    {% endif %}
                </div>
                <div class="well">
                    <div id="disqus_thread"></div>
                    <script type="text/javascript">
                        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
                        var disqus_shortname = 'meedule'; // required: replace example with your forum shortname

                        /* * * DON'T EDIT BELOW THIS LINE * * */
                        (function() {
                            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
                        })();
                    </script>
                    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
                </div>
            </div>

            <div class="span4" id="sidebar">
                <div id="details">
                    <div class="pull-right">
                        {% block commands %}{% endblock %}
                        <a href="javascript:window.print();">Stampa <i class="icon-print"></i></a><br />
                    </div>
                    {% include 'MeeduleMeetingBundle:Meeting:_detail.html.twig' %}
                </div>

                <div id="attendees">
                    {% block attendees %}
                        {% include 'MeeduleMeetingBundle:Meeting:_attendees.html.twig' %}
                    {% endblock %}
                </div>
                {% if not entity.isClosed or references|length > 0 %}
                    <hr />
                    <div id="references">
                        <h5>
                            <span
                                rel="tooltip"
                                title="Aggugi risorse. Google Drive, Youtube o Slideshare sono ottime piattaforme.">Riferimenti</span> <span class="badge">{{ references|length }}</span></h5>
                        {% block references %}
                            {% include 'MeeduleMeetingBundle:Meeting:_references.html.twig' with {'url_reference_delete': url_delete_reference} %}
                        {% endblock %}

                        {% if not entity.isClosed %}
                            <a class="btn btn-success btn-small" data-toggle="#add_reference">Voglio aggiungere un riferimento</a>
                        
                            <form action="{{ path(url_create_reference, {'slug': slug }) }}" method="post" {{ form_enctype(form_reference) }} class="form-vertical" id="add_reference">
                                {{ form_widget(form_reference) }}
                                <button type="submit" class="btn btn-primary btn-small">Aggiungi</button>
                            </form>
                        {% endif %}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}